### ISSUE TITLE
domains changing in CMIP6

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/domain-tables#6]
@gnikulin Could you fill this issue and drop those domains that which will change? I would probably add a column called `mip_era` or something to distinguish between domains in CMIP5 and CMIP6 which (as fas as i understood) have the same `CORDEX_domain`/`domain_id`? We can also split the tables then if that is more convenient.

**Comment by larsbuntemeyer** [comment]
See also #5

**Comment by gnikulin** [comment]
Here I would suggest:

1) to copy  and rename the merged table "rotated-latitude-longitude.csv" to e.g. "CORDEX-CMIP5_all_grids.csv"
 
2) to add CORDEX-CMIP5 prefix to the current files with some renaming "CORDEX-CMIP5_domain_boundaries.csv", "CORDEX-CMIP5_rotated_grids.csv" and "CORDEX-CMIP5_regular_grids.csv" and clean "CORDEX-CMIP5_rotated_grids.csv" leaving only the rotated grids for the 14 continental scale domains.

3) I'll fill "CORDEX-CMIP5_domain_boundaries.csv", now it's only Europe.

We can keep these files as reference and create a new set of the files with  `mip_era` CMIP6 and then I can update domains with new configuration.
